---
abstract: 'Pod::Checker verifies POD documentation contents for compliance with the POD format specifications'
author:
  - 'Marek Rouchal <marekr@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.76, CPAN::Meta::Converter version 2.120351'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Checker
no_index:
  directory:
    - t
    - inc
requires:
  Cwd: 0
  File::Basename: 0
  Pod::Simple: 3.28
  Test::More: 0.6
version: 1.70
